plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/fly/Desktop/學術研究/10_IPE跨專業教育/07_腳本與驗證/腳本/gh-pages-site/ntuh-matching"
publishOrigin = "default"
base = "/Users/fly/Desktop/學術研究/10_IPE跨專業教育/07_腳本與驗證/腳本/gh-pages-site/ntuh-matching"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]